/* ============================================================
   import.test.mjs — getting codes in from every tool.

   Covers the parser directly and then the whole path over HTTP,
   including a real PDF built at test time rather than a fixture
   checked in, so the extractor is exercised against actual
   compressed streams.

   The assertions that matter most are the negative ones. A parser
   that finds codes in a VIN, or invents a description for a
   manufacturer-specific code, is worse than one that finds
   nothing — it produces a confident wrong answer about a repair.
   ============================================================ */
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { parseScanReport } from '../server/scanimport.js';
import { pdfToText } from '../server/pdftext.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; } else { fail++; console.error('  ✗ ' + m); } };
const eq = (a, b, m) => ok(a === b, `${m}  (got ${JSON.stringify(a)}, wanted ${JSON.stringify(b)})`);
const codesOf = r => (r.codes || []).map(c => c.code).sort();
const find = (r, c) => (r.codes || []).find(x => x.code === c);

/* ------------------------------------------------------------
   Build a real PDF: a page whose content stream is Flate-
   compressed, which is what every generator emits.
   ------------------------------------------------------------ */
function makePdf(lines, { ascii85 = false } = {}) {
  let content = 'BT /F1 11 Tf 1 0 0 1 40 750 Tm\n';
  for (const l of lines) {
    content += '(' + String(l).replace(/([()\\])/g, '\\$1') + ') Tj\n0 -16 Td\n';
  }
  content += 'ET';

  let stream = zlib.deflateSync(Buffer.from(content, 'latin1'));
  let filter = '/FlateDecode';
  if (ascii85) {
    /* encode base-85 so the ASCII85 path is exercised too */
    const b = stream;
    let s85 = '';
    for (let i = 0; i < b.length; i += 4) {
      const chunk = b.subarray(i, i + 4);
      const pad = 4 - chunk.length;
      const padded = Buffer.concat([chunk, Buffer.alloc(pad)]);
      let n = padded.readUInt32BE(0);
      const grp = [];
      for (let k = 0; k < 5; k++) { grp.unshift(String.fromCharCode(33 + (n % 85))); n = Math.floor(n / 85); }
      s85 += grp.join('').slice(0, 5 - pad);
    }
    stream = Buffer.from(s85 + '~>', 'latin1');
    filter = '[ /ASCII85Decode /FlateDecode ]';
  }

  const objs = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n'
  ];
  const parts = [Buffer.from('%PDF-1.4\n', 'latin1')];
  for (const o of objs) parts.push(Buffer.from(o, 'latin1'));
  parts.push(Buffer.from(`4 0 obj\n<< /Filter ${filter} /Length ${stream.length} >>\nstream\n`, 'latin1'));
  parts.push(stream);
  parts.push(Buffer.from('\nendstream\nendobj\n', 'latin1'));
  parts.push(Buffer.from('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n', 'latin1'));
  parts.push(Buffer.from('trailer\n<< /Root 1 0 R /Size 6 >>\n%%EOF\n', 'latin1'));
  return Buffer.concat(parts);
}

/* ============================================================
   1. PDF EXTRACTION
   ============================================================ */
console.log('\n  pdf extraction');
{
  const pdf = makePdf([
    'Vehicle Health Report',
    'Generated by RepairSolutions2',
    'VIN: 1FTEW1EF5FKD12345   Odometer: 96,142 mi',
    'P0420 Catalyst System Efficiency Below Threshold (Bank 1)',
    "U0100 Lost Communication With ECM/PCM 'A'"
  ]);
  const t = pdfToText(pdf);
  ok(t.text.includes('P0420'), 'flate-compressed content stream is read');
  ok(t.text.includes('(Bank 1)'), 'balanced parentheses inside a string survive');
  ok(t.text.includes("'A'"), 'apostrophes survive');
  eq(t.imageOnly, false, 'a text PDF is not reported as image-only');

  const a85 = pdfToText(makePdf(['P0301 Cylinder 1 Misfire Detected'], { ascii85: true }));
  ok(a85.text.includes('P0301'), 'ASCII85 + Flate filter chain is decoded');

  const notPdf = pdfToText(Buffer.from('hello world'));
  ok(!!notPdf.error, 'a non-PDF is rejected rather than parsed as noise');
}

/* ============================================================
   2. FORMATS — one report, many exports
   ============================================================ */
console.log('  formats');
{
  const r = parseScanReport(makePdf([
    'RepairSolutions2 Vehicle Report',
    'Odometer: 96,142 mi',
    'P0420 Catalyst System Efficiency Below Threshold (Bank 1)',
    'P0171 System Too Lean (Bank 1) Pending',
    'C0035 Left Front Wheel Speed Sensor Circuit'
  ]), 'report.pdf');
  eq(r.format, 'pdf', 'pdf detected');
  ok(codesOf(r).join(',') === 'C0035,P0171,P0420', 'all three codes read from the PDF');
  eq(r.tool, 'RepairSolutions2 (Innova / Hyper Tough)', 'the HT500\'s app is identified by name');
  eq(r.context.odometer, 96142, 'odometer read from the report');
  eq(find(r, 'P0171').status, 'pending', 'status read from the line');
  eq(find(r, 'P0171').description, 'System Too Lean (Bank 1)',
    'the status word is not left dangling on the end of the description');

  const csv = parseScanReport(
    'Code,Description,Status\n' +
    'P0420,Catalyst System Efficiency Below Threshold Bank 1,Confirmed\n' +
    'P0171,System Too Lean Bank 1,Pending\n' +
    'U0100,"Lost Communication With ECM/PCM, module A",Stored\n', 'x.csv');
  eq(csv.format, 'delimited', 'csv detected');
  eq(csv.codes.length, 3, 'three rows read');
  eq(find(csv, 'U0100').description, 'Lost Communication With ECM/PCM, module A',
    'a quoted comma inside a CSV cell does not split the description');

  const tsv = parseScanReport('DTC\tDefinition\tType\nP0300\tRandom Misfire\tstored\n', 'x.tsv');
  eq(tsv.codes.length, 1, 'tab-separated read');

  const json = parseScanReport(JSON.stringify({
    app: 'Car Scanner ELM OBD2',
    dtcs: [{ code: 'P0300', description: 'Random Misfire Detected', status: 'stored' },
           { code: 'P0128', desc: 'Coolant Thermostat', type: 'pending' }]
  }), 'x.json');
  eq(json.format, 'json', 'json detected');
  eq(json.codes.length, 2, 'nested json array read');
  eq(find(json, 'P0128').status, 'pending', 'alternate status key honoured');

  const html = parseScanReport(
    '<html><body><table>' +
    '<tr><td>P0455</td><td>Evaporative Emission System Leak (large)</td><td>Stored</td></tr>' +
    '<tr><td>P0442</td><td>Evaporative Emission System Leak (small)</td><td>Pending</td></tr>' +
    '</table></body></html>', 'x.html');
  eq(html.format, 'html', 'html detected');
  eq(html.codes.length, 2, 'table rows read');
  ok(/Evaporative/.test(find(html, 'P0455').description), 'cell text kept as the description');

  const email = parseScanReport(
    'Your RepairSolutions2 report\nOdometer: 88300 miles\n\nP0455\nEvaporative Emission System Leak Detected\nP0442 - Small leak - PENDING');
  eq(email.codes.length, 2, 'plain email text read');
  eq(find(email, 'P0455').description, 'Evaporative Emission System Leak Detected',
    'a description on the following line is picked up');
  eq(find(email, 'P0442').status, 'pending', 'inline status read');
}

/* ============================================================
   3. THE NEGATIVE CASES — what it must refuse to do
   ============================================================ */
console.log('  refusals (the important half)');
{
  /* A VIN contains code-shaped substrings. Matching inside one would
     attach a fault to a vehicle that does not have it. */
  const vin = parseScanReport('VIN: 1FTEWC1ABC345XYZ7 and nothing else here');
  ok(!!vin.error, 'no codes invented out of a VIN');

  const vin2 = parseScanReport('VIN JH4KA7561PC008269\nOdometer 55000');
  ok(!!vin2.error, 'no codes invented out of a second VIN');

  /* Adjacent digits mean it is a longer token, not a code. */
  const longer = parseScanReport('Part number P04201 and reference C00351');
  ok(!!longer.error, 'P04201 is not read as P0420');

  /* But a code glued to a word by a kerning-based PDF must still be found. */
  const glued = parseScanReport('P0301Cylinder 1 Misfire Detected');
  eq(codesOf(glued).join(','), 'P0301', 'a code with no space after it is still found');

  const empty = parseScanReport('Oil change receipt, total 45.99', 'r.txt');
  ok(!!empty.error, 'a receipt yields an error, not an empty success');
  ok(/paste its text/i.test(empty.error), 'and suggests what to try next');

  /* Several codes on one line share no description — borrowing the
     neighbour's would mislabel the fault. */
  const multi = parseScanReport('Stored: P0420 P0171 P0300');
  eq(multi.codes.length, 3, 'three codes on one line');
  ok(multi.codes.every(c => !c.description), 'none of them borrows a description');

  /* An image-only PDF must say so rather than silently finding nothing. */
  const imgPdf = Buffer.concat([
    Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /XObject /Subtype /Image /Filter /FlateDecode /Length 8 >>\nstream\n', 'latin1'),
    zlib.deflateSync(Buffer.from('notatext')),
    Buffer.from('\nendstream\nendobj\ntrailer\n<< >>\n%%EOF', 'latin1')
  ]);
  const img = parseScanReport(imgPdf, 'scan.pdf');
  ok(!!img.error, 'an image-only PDF errors');
  ok(/type the codes in directly/i.test(img.error), 'and points at the manual route');
  ok(!/no trouble codes found/i.test(img.error), 'without pretending it read the file');
}

/* ============================================================
   4. OVER HTTP — the whole path
   ============================================================ */
console.log('  end to end');
const DATA = fs.mkdtempSync(path.join(os.tmpdir(), 'garage-imp-'));
const PORT = 2900 + Math.floor(Math.random() * 90);
const BASE = 'http://127.0.0.1:' + PORT;
const srv = spawn(process.execPath, ['server/index.js'], {
  cwd: root, env: { ...process.env, DATA_DIR: DATA, PORT: String(PORT) }, stdio: ['ignore', 'ignore', 'pipe']
});
let srvErr = '';
srv.stderr.on('data', d => { srvErr += d; });
const finish = c => {
  srv.kill('SIGKILL');
  try { fs.rmSync(DATA, { recursive: true, force: true }); } catch { }
  console.log(fail ? `\n  ✗ ${fail} failed, ${pass} passed\n` : `\n  ✓ import: ${pass} assertions passed\n`);
  process.exit(c);
};

try {
  let up = false;
  for (let i = 0; i < 100 && !up; i++) {
    try { await fetch(BASE + '/healthz'); up = true; } catch { await new Promise(r => setTimeout(r, 100)); }
  }
  if (!up) { console.error('server did not start\n' + srvErr); finish(1); }

  let cookie = '';
  const api = async (method, url, body, isForm) => {
    const headers = cookie ? { cookie } : {};
    if (!isForm && body !== undefined) headers['content-type'] = 'application/json';
    const r = await fetch(BASE + '/api' + url, {
      method, headers,
      body: body === undefined ? undefined : (isForm ? body : JSON.stringify(body))
    });
    const sc = r.headers.get('set-cookie');
    if (sc) cookie = sc.split(';')[0];
    let j = null; try { j = await r.json(); } catch { }
    return { status: r.status, body: j };
  };

  await api('POST', '/auth/register', { email: 'imp@test.co', password: 'password123', name: 'Imp' });
  const V = (await api('POST', '/vehicles', { year: 2015, make: 'Ford', model: 'F-150', mileage: 96000 })).body.vehicle.id;

  /* --- typed by hand: the path that works on any phone --- */
  let r = await api('POST', `/vehicles/${V}/codes`, { codes: [{ code: 'p0420' }, { code: 'P0171', status: 'pending' }] });
  eq(r.status, 201, 'typed codes accepted');
  eq(r.body.added, 2, 'both saved');
  ok(r.body.dtcs.every(d => d.source === 'generic_decode'), 'typed codes are marked as generic decodes');
  ok(/catalyst/i.test(r.body.dtcs.find(d => d.code === 'P0420').description || ''), 'P0420 decoded from J2012');

  r = await api('POST', `/vehicles/${V}/codes`, { codes: [{ code: 'NOTACODE' }] });
  eq(r.status, 400, 'nonsense codes rejected');

  /* re-adding an already-open code must not duplicate it */
  r = await api('POST', `/vehicles/${V}/codes`, { codes: [{ code: 'P0420' }] });
  eq(r.body.added, 0, 'an already-open code is not duplicated');
  eq(r.body.duplicates.length, 1, 'and is reported as a duplicate');

  /* --- decode preview --- */
  r = await api('GET', '/decode/P0300');
  eq(r.status, 200, 'decode endpoint responds');
  ok(!!r.body.description, 'and returns a definition');
  eq((await api('GET', '/decode/ZZZZZ')).status, 400, 'invalid code rejected by the decoder');

  /* --- pasted text --- */
  r = await api('POST', `/vehicles/${V}/import-report`, {
    text: 'RepairSolutions2\nOdometer: 96500 mi\nP0455 Evaporative Emission System Leak Detected (large leak)\nC0035 Left Front Wheel Speed Sensor'
  });
  eq(r.status, 201, 'pasted report accepted');
  eq(r.body.added, 2, 'two new codes saved');
  eq(r.body.tool, 'RepairSolutions2 (Innova / Hyper Tough)', 'tool identified over HTTP');
  ok(r.body.dtcs.every(d => d.source === 'imported'), 'descriptions from the report are marked imported');

  const odo = await api('GET', `/vehicles/${V}/analytics?period=ALL`);
  ok(odo.body.odometer.series[0].points.some(p => p.y === 96500),
    'the odometer reading stated in the report is filed as a real reading');

  /* --- uploaded PDF --- */
  const pdf = makePdf([
    'TOPDON Diagnostic Report',
    'P0301 Cylinder 1 Misfire Detected',
    'B1318 Battery Voltage Low'
  ]);
  const fd = new FormData();
  fd.append('file', new Blob([pdf], { type: 'application/pdf' }), 'topdon.pdf');
  r = await api('POST', `/vehicles/${V}/import-file`, fd, true);
  eq(r.status, 201, 'PDF upload accepted');
  eq(r.body.added, 2, 'both codes extracted from the uploaded PDF');
  eq(r.body.format, 'pdf', 'reported as a pdf');
  eq(r.body.tool, 'Topdon', 'Topdon identified');

  /* the uploaded file must not be retained — it is parsed and discarded */
  const uploads = fs.readdirSync(path.join(DATA, 'uploads'));
  ok(!uploads.some(f => /\.pdf$/i.test(f)), 'the uploaded report is not kept on disk after parsing');

  /* --- a file with nothing in it --- */
  const fd2 = new FormData();
  fd2.append('file', new Blob([Buffer.from('just a receipt, 45.99')], { type: 'text/plain' }), 'r.txt');
  r = await api('POST', `/vehicles/${V}/import-file`, fd2, true);
  eq(r.status, 422, 'a file with no codes is refused');
  ok(/no trouble codes/i.test(r.body.error || ''), 'with a message that says so');

  /* --- another account cannot import into this vehicle --- */
  cookie = '';
  await api('POST', '/auth/register', { email: 'other2@test.co', password: 'password123', name: 'O' });
  r = await api('POST', `/vehicles/${V}/codes`, { codes: [{ code: 'P0420' }] });
  ok(r.status === 403 || r.status === 404, 'import refuses a foreign vehicle (got ' + r.status + ')');

  finish(fail ? 1 : 0);
} catch (e) {
  console.error('\n  test crashed:', e);
  console.error(srvErr.slice(-1200));
  finish(1);
}
